### ISSUE TITLE
Currently, it appears that single line case statements need braces.

### ISSUE THREAD

**Issue by schubertr** [TeamShadow/shadow#18]
I was unable to compile the [SwitchTest.shadow](https://github.com/TeamShadow/shadow/blob/master/shadow/test/SwitchTest.shadow) program without fixing it. I was getting this error:

    PARSE ERROR: (SwitchTest.shadow) [17:44] Encountered "out"
    Was expecting:
        "{" ...
    
I went through and adjusted all the single line case statements (and default cases) from this:

    case( 3 ) 
    	out.printLine("Three!");
    case( 4 ) 
    	out.printLine("Four!");

To this:

    case( 3 ) 
    {
	  out.printLine("Three!");
    }					
    case( 4s ) 
    {
	  out.printLine("Four!");
    }			

After doing so, I was able to compile and run the program successfully. I'm not sure if this is an issue for everyone, but it seemed important enough to document.

**Comment by bwittman** [comment]
That's strange.  You're sure that your `shadowc` is pointing at the latest version of shadow.jar?

My `SwitchTest.shadow` works fine.

**Comment by bwittman** [comment]
It's not your fault.  It's the `shadow.jar` file.  For some reason, Maven isn't putting the latest version of the parser in it.  I'm trying to figure out why.

**Comment by schubertr** [comment]
Okay. Still, just to clarify, the only version of shadow.jar I have is the one that we worked on the other day.

**Comment by schubertr** [comment]
The new .jar file fixed this. Thanks.
