### ISSUE TITLE
Console.readLine() fails on empty lines

### ISSUE THREAD

**Issue by Brinsky** [TeamShadow/shadow#28]
If `Console.readLine()` is called and the user submits an empty line, a `shadow:standard@IndexOutOfBoundsException` is thrown.

- Note: tested on Linux with xterm

**Comment by bwittman** [comment]
Fixed by commit 38f292773bd92183401d319d59825d0a44f3e7bd 

The fundamental problem was that `Array.subarray()` could not make zero-length arrays.  Now it can!
