### ISSUE TITLE
Integers default to 0

### ISSUE THREAD

**Issue by schubertr** [TeamShadow/shadow#29]
My apologies if this is not an actual issue, but I could not find anything stating this is intended. When declaring an integer it automatically is given the value 0. For example here is some code I was testing with:

    
    import shadow:io@Console;
    
    class test
    {
    	public main( String[] args ) => ()
    	{
    			Console con;
    			
    			int y = crash();
    			con.printLine("num: " # y);
    			
    	}
    	
    	public crash() => (int x)
    	{
    		int x;
    		return x;
    	}
    
    }

Output:

    num: 0

Again, forgive me if this is intended. It just seemed odd and if it isn't like this for a reason I figured it needed attention.

**Comment by bwittman** [comment]
It is intended that values default to 0 or null.  However, the plan is that
uninitialized variables should not be able to be used.  Right now, the
compiler doesn't have the data-flow analysis needed to see if a variable is
initialized or not.  One day, that code will throw an error.

Thanks for the reminder.

**Comment by bwittman** [comment]
Fixed. Commit 9e45fa70999f420ceafe18cfdf0fa37bd2d178af uses SSA to detect when local variables are used without being defined first.
