### ISSUE TITLE
OSX install.sh is lacking

### ISSUE THREAD

**Issue by schubertr** [TeamShadow/shadow#40]
the install.sh script for OSX is missing some serious functionality. I acquired an older mac pro and did a clean install of el capitan on it. Now, trying to install shadow, I am running into a lot of problems. It is missing a lot of needed utilities (JDK, Homebrew, llvm, command line tools for osx, etc) but we only have checks for homebrew and llvm. Once l figure out exactly what this clean install needs in order to install and run shadow, I will update the install.sh file with necessary checks.

**Comment by schubertr** [comment]
After installing what I believe are the necessary things, I get this error when running the `shadox` command.

    Error: Could not find or load main class 2.shadow.shadow.jar

**Comment by bwittman** [comment]
Thanks for checking up on it.  We expect people to have a JDK, but we could put a check in the script to warn people who don't.  That error message looks odd.  It looks as if the wrong jar is being specified by the script, but the same jar should be specified for the `shadowc` command as well.  Does `shadowc` work?

**Comment by schubertr** [comment]
ryans-mac-pro:~ Ryan$ shadowc
    Error: Unable to access jarfile /Volumes/Storage

**Comment by bwittman** [comment]
The 0.7.5 release has a much-improved macOS install script. 
 Check it out: https://github.com/TeamShadow/shadow/tree/v0.7.5-beta
