### ISSUE TITLE
Shadox not working with get/set

### ISSUE THREAD

**Issue by claude-abounegm** [TeamShadow/shadow#46]
The documentation currently generated only works correctly with methods, and constants. It also works with get/set methods, for example the method: `public get wombat() => (Wombat)` has its description generated correctly; however, `get Wombat wombat` does not get its description generated correctly.

Since `main` was declared as a method getter, the description was correct. However, `parent` was declared as `get nullable Thread parent` and the description does not appear, as shown below:

![screenshot 36](https://cloud.githubusercontent.com/assets/11809881/20372864/48ca37ee-ac3c-11e6-82d4-1b9936112adc.png)

**Comment by bwittman** [comment]
Fixed by a6c14193e30818120f22be63caae2bce70f664dc.
