### ISSUE TITLE
Nullable Interfaces

### ISSUE THREAD

**Issue by claude-abounegm** [TeamShadow/shadow#47]
Nullable interfaces do not work as expected. As soon as we set an interface to nullable, a `check()` on that will not crash the program but calling a method on it will not work.

For example:
```
nullable CanRun runner = null;
...
(set runner to something relevant)
...
check(runner).run(); // does not work
```

**Comment by bwittman** [comment]
Fixed by https://github.com/TeamShadow/shadow/commit/fe82856bb30e1142e9c6e4de654f4643678647fa
