### ISSUE TITLE
shadowc errors when Windows 7 install path contains spaces

### ISSUE THREAD

**Issue by Brinsky** [TeamShadow/shadow#71]
I recently installed Shadow 0.7.5 on my Windows 7 machine in the directory ```C:\Program Files\Shadow\```. When I compile a program using the Eclipse plug-in, I get this error:

```opt: C:\Program%20Files\Shadow\shadow\Unwind64.ll: error: Could not open input file: no such file or directory```

It seems as though shell commands on Windows do not use the ```%20``` syntax to represent spaces, they instead seem to require the path specified verbatim in quotation marks. The directory name appears to be stored correctly in my ```SHADOW_HOME``` environment variable, so it seems likely that the path handling code either in Configuration or in Main itself is at fault.

**Comment by bwittman** [comment]
Fixed by 281534fc7b76cdf28584f8290aaa68f1a6950e29
